import {DropdownOption} from '../../types/dropdown-option.type.ts';

export const DISPLAY_OPTIONS: DropdownOption<string>[] = [
	{label: 'Block', value: 'block', key: 'block'},
	{label: 'Inline', value: 'inline', key: 'inline'},
	{label: 'Inline Block', value: 'inline-block', key: 'inline-block'},
	{label: 'Flex', value: 'flex', key: 'flex'},
	{label: 'Inline Flex', value: 'inline-flex', key: 'inline-flex'},
	{label: 'Grid', value: 'grid', key: 'grid'},
	{label: 'Inline Grid', value: 'inline-grid', key: 'inline-grid'},
	{label: 'Flow Root', value: 'flow-root', key: 'flow-root'},
	{label: 'None', value: 'none', key: 'none'},
	{label: 'Contents', value: 'contents', key: 'contents'},
	{label: 'Block Flow', value: 'block flow', key: 'block flow'},
	{label: 'Inline Flow', value: 'inline flow', key: 'inline flow'},
	{label: 'Inline Flow Root', value: 'inline flow-root', key: 'inline flow-root'},
	{label: 'Block Flex', value: 'block flex', key: 'block flex'},
	{label: 'Inline Flex', value: 'inline flex', key: 'inline flex'},
	{label: 'Block Grid', value: 'block grid', key: 'block grid'},
	{label: 'Inline Grid', value: 'inline grid', key: 'inline grid'},
	{label: 'Block Flow Root', value: 'block flow-root', key: 'block flow-root'},
	{label: 'Table', value: 'table', key: 'table'},
	{label: 'Table Row', value: 'table-row', key: 'table-row'},
	{label: 'List Item', value: 'list-item', key: 'list-item'},
	{label: 'Inherit', value: 'inherit', key: 'inherit'},
	{label: 'Initial', value: 'initial', key: 'initial'},
	{label: 'Revert', value: 'revert', key: 'revert'},
	{label: 'Revert Layer', value: 'revert-layer', key: 'revert-layer'},
	{label: 'Unset', value: 'unset', key: 'unset'},
];
