import {ItemValueUnit} from '../../../types/enums/item-value-unit.enum.ts';
import {ItemFields} from './item.fields.ts';
import {Item} from '../../../types/item.type.ts';

export const itemInitialValues: ItemFields = {
	name: '',
	text: '',
	width: '',
	widthUnit: ItemValueUnit.PIXEL,
	height: '',
	heightUnit: ItemValueUnit.PIXEL,
	display: 'block',
	position: 'relative',
	color: '',
	paddingTop: '',
	paddingTopUnit: ItemValueUnit.PIXEL,
	paddingRight: '',
	paddingRightUnit: ItemValueUnit.PIXEL,
	paddingBottom: '',
	paddingBottomUnit: ItemValueUnit.PIXEL,
	paddingLeft: '',
	paddingLeftUnit: ItemValueUnit.PIXEL,
	marginTop: '',
	marginTopUnit: ItemValueUnit.PIXEL,
	marginRight: '',
	marginRightUnit: ItemValueUnit.PIXEL,
	marginBottom: '',
	marginBottomUnit: ItemValueUnit.PIXEL,
	marginLeft: '',
	marginLeftUnit: ItemValueUnit.PIXEL,
};

export const generateItemInitialValues = ({width, height, color, padding, margin, ...item}: Item): ItemFields => ({
	...itemInitialValues,
	...item,
	width: `${width.value}`,
	widthUnit: width.unit,
	height: `${height.value}`,
	heightUnit: height.unit,
	color: color || '',
	paddingTop: `${padding.top.value}`,
	paddingTopUnit: padding.top.unit,
	paddingRight: `${padding.right.value}`,
	paddingRightUnit: padding.right.unit,
	paddingBottom: `${padding.bottom.value}`,
	paddingBottomUnit: padding.bottom.unit,
	paddingLeft: `${padding.left.value}`,
	paddingLeftUnit: padding.left.unit,
	marginTop: `${margin.top.value}`,
	marginTopUnit: margin.top.unit,
	marginRight: `${margin.right.value}`,
	marginRightUnit: margin.right.unit,
	marginBottom: `${margin.bottom.value}`,
	marginBottomUnit: margin.bottom.unit,
	marginLeft: `${margin.left.value}`,
	marginLeftUnit: margin.left.unit,
});
